version: "3.9"
services:
  nginx:
    container_name: symfony
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./infra/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
  #   depends_on:
  #     - redis
  #     - mariadb
  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'symfonyredis:/data'
  #   networks:
  #     - symfony
  # mariadb:
  #   image: 'mariadb:latest'
  #   ports:
  #     - '3306'
  #   expose:
  #     - '3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_DATABASE: '${DB_DATABASE}'
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #   volumes:
  #     - 'symfonymariadb:/var/lib/mysql'
  #   networks:
  #     - symfony
  # mailhog:
  #   image: 'mailhog/mailhog:latest'
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - symfony

networks:
  symfony:
    driver: bridge

# volumes:
#   symfonymariadb:
#     driver: local
#   symfonyredis:
#     driver: local